name: Build nab App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ نصب Qt 6.9.0 MSVC (به‌روزرسانی‌شده به آخرین نسخه)
    - name: Install Qt 6.9.0 MSVC
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtwebengine qttools'
        cache: true
        cache-key-prefix: 'qt-6.9.0'
        aqtversion: '==3.1.19'  # رفع خطای Python با نسخه پایدار aqtinstall

    # 3️⃣ تنظیم محیط MSVC 2022
    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo PATH=%PATH%

    # 4️⃣ بیلد پروژه با qmake و nmake (داخل پوشه OpenBoard-master)
    - name: Build project
      shell: cmd
      run: |
        dir
        if not exist OpenBoard-master echo "OpenBoard-master folder not found!" && exit 1
        cd OpenBoard-master
        dir
        if not exist OpenBoard.pro echo "OpenBoard.pro not found in OpenBoard-master!" && exit 1
        qmake OpenBoard.pro -spec win32-msvc
        nmake release

    # 5️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        cd OpenBoard-master
        mkdir ..\deploy
        dir release
        if exist release\nab.exe move release\nab.exe ..\deploy\
        if not exist ..\deploy\nab.exe echo "No nab.exe found in release!" && exit 1
        cd ..\deploy
        windeployqt nab.exe --release --no-translations --no-opengl-sw

    # 6️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
