name: Build OpenBoard App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ کلون کردن ریپازیتوری ThirdParty
    - name: Clone ThirdParty repository
      run: git clone https://github.com/OpenBoard-org/OpenBoard-ThirdParty.git

    # 3️⃣ نصب Qt 6.9.2 MSVC با WebEngine
    - name: Install Qt 6.9.2 MSVC with WebEngine
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtwebengine'
        cache: true
        cache-key-prefix: 'qt-6.9.2'

    # 4️⃣ تنظیم محیط MSVC
    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    # 5️⃣ بیلد کتابخانه‌های ThirdParty و پروژه اصلی
    - name: Build project
      shell: cmd
      run: |
        cd OpenBoard-ThirdParty\freetype
        qmake freetype.pro
        nmake
        cd ..\quazip
        qmake quazip.pro
        nmake
        cd ..\xpdf
        qmake xpdf.pro
        nmake
        cd ..\..
        qmake OpenBoard.pro
        nmake

    # 6️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        mkdir deploy
        move build\win64\release\product\nab.exe deploy\
        cd deploy
        windeployqt OpenBoard.exe --qmldir ..\..\src\qml

    # 7️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
