name: Build nab App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ نصب Python و aqtinstall (جایگزین install-qt-action برای رفع خطای Python)
    - name: Setup Python and install aqtinstall
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall==3.3.0

    # 3️⃣ نصب Qt 6.9.0 MSVC با aqt
    - name: Install Qt 6.9.0 MSVC
      shell: cmd
      run: |
        aqt install-qt windows desktop 6.9.0 win64_msvc2022_64 -o C:\Qt\6.9.0\msvc2022_64 --modules qtwebengine,qttools
        set QTDIR=C:\Qt\6.9.0\msvc2022_64
        set PATH=%QTDIR%\bin;%PATH%

    # 4️⃣ تنظیم محیط MSVC 2022
    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo PATH=%PATH%

    # 5️⃣ بیلد پروژه با qmake و nmake (داخل پوشه OpenBoard-master)
    - name: Build project
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set QTDIR=C:\Qt\6.9.0\msvc2022_64
        set PATH=%QTDIR%\bin;%PATH%
        echo PATH=%PATH%
        dir
        if not exist OpenBoard-master echo "OpenBoard-master folder not found!" && exit 1
        cd OpenBoard-master
        dir
        if not exist OpenBoard.pro echo "OpenBoard.pro not found in OpenBoard-master!" && exit 1
        qmake OpenBoard.pro -spec win32-msvc
        nmake release

    # 6️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set QTDIR=C:\Qt\6.9.0\msvc2022_64
        set PATH=%QTDIR%\bin;%PATH%
        cd OpenBoard-master
        mkdir ..\deploy
        dir release
        if exist release\nab.exe move release\nab.exe ..\deploy\
        if not exist ..\deploy\nab.exe echo "No nab.exe found in release!" && exit 1
        cd ..\deploy
        windeployqt nab.exe --release --no-translations --no-opengl-sw

    # 7️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
        retention-days: 7
