name: Build na App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ نصب Qt 6.5.3 MSVC
    - name: Install Qt 6.5.3 MSVC
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtwebengine qttools'
        cache: true
        cache-key-prefix: 'qt-6.5.3'

    # 3️⃣ تنظیم محیط MSVC 2019
    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    # 4️⃣ بیلد پروژه با qmake و nmake
    - name: Build project
      shell: cmd
      run: |
        dir OpenBoard-master
        if not exist OpenBoard.pro echo "na.pro not found!" && exit 1
        qmake OpenBoard.pro -spec win32-msvc
        nmake release

    # 5️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        mkdir deploy
        dir release
        if exist release\nab.exe move release\nab.exe deploy\
        if not exist deploy\nab.exe echo "No nab.exe found in release!" && exit 1
        cd deploy
        windeployqt na.exe --release --no-translations --no-opengl-sw

    # 6️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
        retention-days: 7
