name: Build nab App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ کلون کردن ریپازیتوری ThirdParty
    - name: Clone ThirdParty repository
      run: git clone https://github.com/OpenBoard-org/OpenBoard-ThirdParty.git

    # 3️⃣ نصب Python و aqtinstall
    - name: Setup Python and install aqtinstall
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall==3.1.19

    # 4️⃣ نصب Qt 5.15.2 MSVC 2019
    - name: Install Qt 5.15.2 MSVC
      shell: cmd
      run: |
        aqt install-qt --outputdir C:\Qt windows desktop 5.15.2 win64_msvc2019_64 --modules qtwebengine qttools qtscript qtmultimedia qtdeclarative qtsvg
        set QTDIR=C:\Qt\5.15.2\msvc2019_64
        set PATH=%QTDIR%\bin;%PATH%

    # 5️⃣ تنظیم محیط MSVC 2019 با action
    - name: Setup MSVC 2019
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16'

    # 6️⃣ تنظیم vcvars و PATH
    - name: Setup vcvars and PATH
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        echo PATH=%PATH%

    # 7️⃣ بیلد کتابخانه‌های ThirdParty
    - name: Build ThirdParty libraries
      shell: cmd
      run: |
        set QTDIR=C:\Qt\5.15.2\msvc2019_64
        set PATH=%QTDIR%\bin;%PATH%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        cd OpenBoard-ThirdParty\freetype
        qmake freetype.pro -spec win32-msvc CONFIG+=release
        nmake
        cd ..\quazip
        qmake quazip.pro -spec win32-msvc CONFIG+=release
        nmake
        cd ..\xpdf
        qmake xpdf.pro -spec win32-msvc CONFIG+=release
        nmake

    # 8️⃣ بیلد پروژه با qmake و nmake (داخل پوشه OpenBoard-master)
    - name: Build project
      shell: cmd
      run: |
        set QTDIR=C:\Qt\5.15.2\msvc2019_64
        set PATH=%QTDIR%\bin;%PATH%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        echo PATH=%PATH%
        dir
        if not exist OpenBoard-master echo "OpenBoard-master folder not found!" && exit 1
        cd OpenBoard-master
        dir
        if not exist OpenBoard.pro echo "OpenBoard.pro not found in OpenBoard-master!" && exit 1
        qmake OpenBoard.pro -spec win32-msvc CONFIG+=release
        nmake

    # 9️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        set QTDIR=C:\Qt\5.15.2\msvc2019_64
        set PATH=%QTDIR%\bin;%PATH%
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" || call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        cd OpenBoard-master
        mkdir ..\deploy
        dir build\win64\release\product
        if exist build\win64\release\product\nab.exe move build\win64\release\product\nab.exe ..\deploy\
        if not exist ..\deploy\nab.exe echo "No nab.exe found!" && exit 1
        cd ..\deploy
        windeployqt nab.exe --release --no-translations --no-opengl-sw --qmldir ..\OpenBoard-master\resources\qml

    # 10️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
        retention-days: 7
