name: Build nab App exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ گرفتن کدها از مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ نصب Python 3.11 (برای سازگاری بهتر با install-qt-action)
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3️⃣ نصب Qt 6.6.3 MSVC
    - name: Install Qt 6.6.3 MSVC
      uses: jurplel/install-qt-action@v4.1.0
      with:
        version: '6.6.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtwebengine qttools'
        cache: true
        cache-key-prefix: 'qt-6.6.3-${{ github.sha }}'

    # 4️⃣ تنظیم محیط MSVC 2019
    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo PATH=%PATH%

    # 5️⃣ بیلد پروژه با qmake و nmake (داخل پوشه OpenBoard-master)
    - name: Build project
      shell: cmd
      run: |
        dir
        if not exist OpenBoard-master echo "OpenBoard-master folder not found!" && exit 1
        cd OpenBoard-master
        dir
        if not exist OpenBoard.pro echo "OpenBoard.pro not found in OpenBoard-master!" && exit 1
        qmake OpenBoard.pro -spec win32-msvc
        nmake release

    # 6️⃣ جمع‌آوری فایل‌های مورد نیاز با windeployqt
    - name: Deploy application
      shell: cmd
      run: |
        cd OpenBoard-master
        mkdir ..\deploy
        dir release
        if exist release\nab.exe move release\nab.exe ..\deploy\
        if not exist ..\deploy\nab.exe echo "No nab.exe found in release!" && exit 1
        cd ..\deploy
        windeployqt nab.exe --release --no-translations --no-opengl-sw

    # 7️⃣ آپلود فایل exe به عنوان artifact
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: nab-exe
        path: deploy\nab.exe
